### PR TITLE
Tsai wu failure criteria

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
Addressing Issue number 13 on the calculator planning spread sheet.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jacobdeery, @JaredWatson, @KavinSatheeskumar, and @kittykong5124)

___
*[Code.py, line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKza7_X8ZbF7v9j2A0k:-MKza7_X8ZbF7v9j2A0l:b-f6tv4a) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L118)):*
> ```Python
> ## get an explanation as to what they all really mean]
> 
> def tsai_wu(F1t, F1c, F2t, F2c, F12, s1, s2, s12):
> ```

Let's take advantage of this PR to start structuring the code a bit better. Right now we have everything in one file, but it would be much cleaner to define these functions in a separate file so that they can be tested properly. Let's create a separate Python file for at least the `tsai_wu` function (I'll defer to Shirley on what it should be named).
___
*[Code.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzbgq75_oFy291jThw:-MKzbgq75_oFy291jThx:b-tzsv05) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L150)):*
> ```
> len(height)
> ```
using `len(height)` here is technically correct, but it would be more clear what this number represents if we declared a variable named `num_layers`.
___
*[Code.py, line 152 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzauhpElRtMKrqgZ-y:-MKzauhpElRtMKrqgZ-z:b-u2f15w) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L152)):*
> ```
> np.array([[1,1,1,1,1] for _ in range(len(height))])
> ```
this can just be `np.ones((len(height), 5))`
___
*[Code.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzagk9-_4lbFinK6vm:-MKzagk9-_4lbFinK6vn:bdhpd77) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L165)):*
> ```
>             plystresses[i][3]
> ```
`plystresses` is an Nx3 matrix, so `plystresses[i][3]` is not defined. I suspect you want 0, 1, and 2 here instead of 0, 2, and 3.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jacobdeery, @JaredWatson, and @kittykong5124)

___
*[Code.py, line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKza7_X8ZbF7v9j2A0k:-MKzemWn5m1VD9X1iKxV:b-105efy) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L118)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Let's take advantage of this PR to start structuring the code a bit better. Right now we have everything in one file, but it would be much cleaner to define these functions in a separate file so that they can be tested properly. Let's create a separate Python file for at least the `tsai_wu` function (I'll defer to Shirley on what it should be named).
</blockquote></details>

There is a file on the rocketry drive called "Yet-to-be-named composite calculator". There it has a big flow chart with a bunch of functions basically describing how the calculator will work. It might be a good idea to have each of those functions as a separate file and the main calculator could just be an implementation of the flow chart.

https://docs.google.com/document/d/1EUArXqN0vijeUADVOBy0AGrnSFto_sec8g0qTr2wjF8/edit
___
*[Code.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzbgq75_oFy291jThw:-MKzfXZD13k5eqbmevQY:b-9kbly3) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L150)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> len(height)
> ```
using `len(height)` here is technically correct, but it would be more clear what this number represents if we declared a variable named `num_layers`.
</blockquote></details>

I'm just following the same conventions that Shirley used. In future drafts of this pull request, I can edit the code to make sure num_layers is used in place of every len(height).
___
*[Code.py, line 152 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzauhpElRtMKrqgZ-y:-MKzfjKp996HZHmTYeH0:b-vh7jss) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L152)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> np.array([[1,1,1,1,1] for _ in range(len(height))])
> ```
this can just be `np.ones((len(height), 5))`
</blockquote></details>

Ok, will do
___
*[Code.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzagk9-_4lbFinK6vm:-MKzfUyq97xxG6lX6XvI:b-x2bub5) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L165)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             plystresses[i][3]
> ```
`plystresses` is an Nx3 matrix, so `plystresses[i][3]` is not defined. I suspect you want 0, 1, and 2 here instead of 0, 2, and 3.
</blockquote></details>

Ah thanks.

**Review by kittykong5124 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @jacobdeery, @JaredWatson, @KavinSatheeskumar, and @kittykong5124)

___
*[Code.py, line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKza7_X8ZbF7v9j2A0k:-MLDxh3s6cDg8yazT5ML:bkw1r92) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L118)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

There is a file on the rocketry drive called "Yet-to-be-named composite calculator". There it has a big flow chart with a bunch of functions basically describing how the calculator will work. It might be a good idea to have each of those functions as a separate file and the main calculator could just be an implementation of the flow chart.

https://docs.google.com/document/d/1EUArXqN0vijeUADVOBy0AGrnSFto_sec8g0qTr2wjF8/edit
</blockquote></details>

+1 on making the tsai_wu function separate. I'm hoping to split up the rest of the code as functions in the way that you suggested based off the flowchart, and we can just call those functions in the main code I think. Based off what I have seen of Topside, we just need to make a folder with all the functions and an __init__.py file in it. 
___
*[Code.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzbgq75_oFy291jThw:-MLEAFI06wT_TX8sKeGO:b-npe8kq) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L150)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I'm just following the same conventions that Shirley used. In future drafts of this pull request, I can edit the code to make sure num_layers is used in place of every len(height).
</blockquote></details>

I'd support creating a variable for len(height). I would prefer naming it ply_num since the word "layers" isn't really used anywhere else in the code. However, before making this change I want to discuss how the merge process for our two branches is going to go.
___
*[Code.py, line 110 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE0Sb_0nENah8ep9pG:-MLE0Sb_0nENah8ep9pH:b-eeh88g) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L110)):*
> ```Python
> 
> ## The Tsai-Wu failure Criteria for laminates.
> ## If the expresion given is greater than 1 for any of the
> ```

Greater than or equal to
___
*[Code.py, line 116 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE86BW3ADcG6Cmt-UU:-MLE86BW3ADcG6Cmt-UV:btlo3eb) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L116)):*
> ```Python
> ## experiencing to determine if the laminate will fail.
> ## [Note, I'll define all the variable names once I can
> ## get an explanation as to what they all really mean]
> ```

The definitions for these variables can be found in Chapter 6 of the lecture slides: https://drive.google.com/file/d/18JKvAY_EiHs60VrFIUQUbHYxspwufKh0/view?usp=sharing
___
*[Code.py, line 118 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLDzddW1FY37Ob5TPNv:-MLDzddW1FY37Ob5TPNw:b550611) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L118)):*
> ```Python
> ## get an explanation as to what they all really mean]
> 
> def tsai_wu(F1t, F1c, F2t, F2c, F12, s1, s2, s12):
> ```

In the "unfinished" branch, there is some code that calculates and plots the stress in each ply. the array that contains the stresses in each ply is called plystress_loc (loc short for local, v.s. glob short for global) so I think it would be better to refer to the stresses as plystress1, plystress2, plystress12
___
*[Code.py, line 130 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE8WO-BdUDyz487EoX:-MLE8WO-BdUDyz487EoY:baj3i9) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L130)):*
> ```Python
> ## The following code assumes that an arrays called
> ## plystresses will be created in the following form
> ## plystresses = [
> ```

As mentioned in an earlier comment, the array exists already as plystress_loc and is a 3xn array, whereas the plystresses array you've defined in the comment is nx3 where n is the number of plies. Not your fault, I forgot that those changes were in a branch and should've made you aware of them.
___
*[Code.py, line 139 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE9iOHCM7jLdwa703l:-MLE9iOHCM7jLdwa703m:b-t9b1rx) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L139)):*
> ```Python
> ## for the ply at stack[i]
> 
> ## maxstresses = [
> ```

My comment regarding the dimensions of plystresses applies to maxstresses as well. For consistency, we should name this function "maxstress" and have it be a 5xn array
___
*[Code.py, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLEC3AW7dXcBIWwtYtU:-MLEC3AX2jdJ1COtVgYn:b-xaf6sb) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L171)):*
> ```Python
>         print(tsai_wu_value)
>         has_not_failed = False
>         print("There was a failure in layer " + str(i+1))
> ```

Please use "ply" instead of "layer". Technically nothing wrong with calling the plies layers, but it's just more conventional and consistent with the rest of the code.

Also, I may have mentioned this on Slack but I think a more useful representation of the tsai wu result would be to take the reciprocal of the number, which will give the FOS for each layer. Since we want to be extra conservative, any FOS lower than around 3 should be a sign to look into how the laminate can be modified to increase the FOS. This might be via looking at a plot of the stress space, or simply changing the laminate parameters until we get a more favourable FOS.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @jacobdeery, @JaredWatson, @KavinSatheeskumar, and @kittykong5124)

___
*[Code.py, line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKza7_X8ZbF7v9j2A0k:-MLL5wjdC48zfQgp2NT4:b-gvkkgk) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L118)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

+1 on making the tsai_wu function separate. I'm hoping to split up the rest of the code as functions in the way that you suggested based off the flowchart, and we can just call those functions in the main code I think. Based off what I have seen of Topside, we just need to make a folder with all the functions and an __init__.py file in it. 
</blockquote></details>

Tsai-Wu has been split of into a different file. @kittykong5124 has said that she will take care of splitting up the rest of the code
___
*[Code.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MKzbgq75_oFy291jThw:-MLL6Jlw-puWLS8ijxwc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2606db59e780c4bb8368b3efca2ee9ee91d7c166/Code.py#L150)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

I'd support creating a variable for len(height). I would prefer naming it ply_num since the word "layers" isn't really used anywhere else in the code. However, before making this change I want to discuss how the merge process for our two branches is going to go.
</blockquote></details>

Done.
___
*[Code.py, line 110 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE0Sb_0nENah8ep9pG:-MLL5vBlE9GJjgS7N-MM:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L110)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

Greater than or equal to
</blockquote></details>

Done.
___
*[Code.py, line 116 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE86BW3ADcG6Cmt-UU:-MLL6M9BCPX338h-UMxo:b6tlgcn) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L116)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

The definitions for these variables can be found in Chapter 6 of the lecture slides: https://drive.google.com/file/d/18JKvAY_EiHs60VrFIUQUbHYxspwufKh0/view?usp=sharing
</blockquote></details>

Will do soon
___
*[Code.py, line 118 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLDzddW1FY37Ob5TPNv:-MLL66R23rCvY0h6zld5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L118)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

In the "unfinished" branch, there is some code that calculates and plots the stress in each ply. the array that contains the stresses in each ply is called plystress_loc (loc short for local, v.s. glob short for global) so I think it would be better to refer to the stresses as plystress1, plystress2, plystress12
</blockquote></details>

Done.
___
*[Code.py, line 130 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE8WO-BdUDyz487EoX:-MLL69IS7Z6KCx1FwivQ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L130)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

As mentioned in an earlier comment, the array exists already as plystress_loc and is a 3xn array, whereas the plystresses array you've defined in the comment is nx3 where n is the number of plies. Not your fault, I forgot that those changes were in a branch and should've made you aware of them.
</blockquote></details>

Done.
___
*[Code.py, line 139 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE9iOHCM7jLdwa703l:-MLL69lH8ckkBJG9tA-A:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L139)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

My comment regarding the dimensions of plystresses applies to maxstresses as well. For consistency, we should name this function "maxstress" and have it be a 5xn array
</blockquote></details>

Done.
___
*[Code.py, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLEC3AW7dXcBIWwtYtU:-MLL6Bek0K042n9KGqH1:begi371) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L171)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

Please use "ply" instead of "layer". Technically nothing wrong with calling the plies layers, but it's just more conventional and consistent with the rest of the code.

Also, I may have mentioned this on Slack but I think a more useful representation of the tsai wu result would be to take the reciprocal of the number, which will give the FOS for each layer. Since we want to be extra conservative, any FOS lower than around 3 should be a sign to look into how the laminate can be modified to increase the FOS. This might be via looking at a plot of the stress space, or simply changing the laminate parameters until we get a more favourable FOS.
</blockquote></details>

that print statement was removed. In the new variables related to it, ply is used in place of layer

**Review by jacobdeery — COMMENTED** [review]
I would like to see some unit tests for the new functions, but it's not critical to include in this PR.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-:-MLd4r3HDK85qA11iznK:b-70gc90)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @JaredWatson, @KavinSatheeskumar, and @kittykong5124)

___
*[tsai_wu.py, line 8 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2nSG2ADJ0RQuoOEH:-MLd2nSG2ADJ0RQuoOEI:ba64p88) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L8)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> ## The Tsai-Wu failure Criteria for laminates.
> ## If the expresion given is greater than or equal to
> ## 1 for any of the layers of the laminate, the laminate will fail.
> ## The expression takes as input the maximum stresses
> ## The laminate can take as well as the stresses it is curretly
> ## experiencing to determine if the laminate will fail.
> ## [Note, I'll define all the variable names once I can
> ## get an explanation as to what they all really mean]
> ```
</details>


This comment would be better as a [docstring](https://www.python.org/dev/peps/pep-0257/) written inside the function itself. You can see some examples of how we typically write docstrings in [Topside](https://github.com/waterloo-rocketry/topside/blob/a7c1cda70bfc8ea4d0a2af2e34a7e938741ba68c/topside/plumbing/plumbing_engine.py#L13).
___
*[tsai_wu.py, line 25 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4-MrC3ALZmYG2ZEV:-MLd3z2yAQTV43Bwhbv-:b-cnh9e9) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L25)):*
> ```Python
>             2*f12*plystress1*plystress2)
> 
> ## The following code assumes that an arrays called
> ```

Same as above; this would be best as a docstring.
___
*[tsai_wu.py, line 63 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2wO_61dEF63HxaHp:-MLd2wO_61dEF63HxaHq:b-fddb5q) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L63)):*
> ```
> indicies
> ```
indices
___
*[tsai_wu.py, line 64 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2toC3Qs7W9HjEiMq:-MLd2toC3Qs7W9HjEiMr:bj6onab) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L64)):*
> ```
> recripricol
> ```
reciprocal
___
*[__pycache__/tsai_wu.cpython-38.pyc, line 0 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2aB3BIjhas3NQVT4:-MLd2aB3BIjhas3NQVT5:b-xk29f5) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/__pycache__/tsai_wu.cpython-38.pyc#L0)):*
This file should not be in the commit. We should add a .gitignore so that git automatically ignores it, but that can be a separate PR. For now, please just remove it from this PR.
___
*[Code.py, line 112 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4PhzCev-OT97rWLt:-MLd4PhzCev-OT97rWLu:balr0f6) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/Code.py#L112)):*
> ```
> len(height)
> ```
`ply_num`
___
*[Code.py, line 113 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4E2o7wTyq3OncPE-:-MLd4E2o7wTyq3OncPE0:bjrsde6) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/Code.py#L113)):*
> ```Python
> #temporary values to input into the function to ensure it works
> plystresses = np.ones(shape=(3,len(height)))
> maxstresses = np.array([[0.5 for _ in range(len(height))] for __ in range(5)])
> ```

this can be `maxstresses = np.full(0.5, (5, ply_num))`

**Review by kittykong5124 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @JaredWatson, @KavinSatheeskumar, and @kittykong5124)

___
*[tsai_wu.py, line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MM3LN0d-NlfmcDTUHj_:-MM3LN0d-NlfmcDTUHja:b2oz9d9) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L35)):*
> ```Python
> ## for the ply at stack[i]
> 
> ## maxstresses = [
> ```

Can you do a find and replace "maxstresses" with "maxstress"?
___
*[tsai_wu.py, line 47 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MM3NcY5Ch3GBQl5ZZAC:-MM3NcY5Ch3GBQl5ZZAD:b165jp5) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L47)):*
> ```Python
> ##len(plystress) = len(maxstresses)
> 
> #plystress = np.zeros(shape=(3,len(height)))
> ```

I think len(height) should be ply_num

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @kittykong5124)

___
*[tsai_wu.py, line 63 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2wO_61dEF63HxaHp:-MM8y33gEaezyMIvx_Bv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L63)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> indicies
> ```
indices
</blockquote></details>

Done.
___
*[tsai_wu.py, line 64 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2toC3Qs7W9HjEiMq:-MM8y3SS3eLsbtxa24fe:b-igyjy7) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L64)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recripricol
> ```
reciprocal
</blockquote></details>

I'm a CS student, not an english student, ok? (on another note, done)
___
*[__pycache__/tsai_wu.cpython-38.pyc, line  at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2aB3BIjhas3NQVT4:-MM8yPsM-TSDyU1IEI3i:bkk0sbb) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/__pycache__/tsai_wu.cpython-38.pyc#L)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

This file should not be in the commit. We should add a .gitignore so that git automatically ignores it, but that can be a separate PR. For now, please just remove it from this PR.
</blockquote></details>

Ok, will remove and save else where
___
*[Code.py, line 112 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4PhzCev-OT97rWLt:-MM8fN0K-o-j7Xk2r7j5:b-7ql1td) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/Code.py#L112)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> len(height)
> ```
`ply_num`
</blockquote></details>

fixed
___
*[Code.py, line 113 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4E2o7wTyq3OncPE-:-MM8fcd15BtQV_dVZrwz:b-fd9x5y) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/Code.py#L113)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

this can be `maxstresses = np.full(0.5, (5, ply_num))`
</blockquote></details>

Uuugggghhh, fine, I guess fancy list-for-loop shenanigans get no love here, fixed

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @jacobdeery and @kittykong5124)

___
*[tsai_wu.py, line 8 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2nSG2ADJ0RQuoOEH:-MM8yoJu7RT2E_8v6GfT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L8)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ## The Tsai-Wu failure Criteria for laminates.
> ## If the expresion given is greater than or equal to
> ## 1 for any of the layers of the laminate, the laminate will fail.
> ## The expression takes as input the maximum stresses
> ## The laminate can take as well as the stresses it is curretly
> ## experiencing to determine if the laminate will fail.
> ## [Note, I'll define all the variable names once I can
> ## get an explanation as to what they all really mean]
> ```

This comment would be better as a [docstring](https://www.python.org/dev/peps/pep-0257/) written inside the function itself. You can see some examples of how we typically write docstrings in [Topside](https://github.com/waterloo-rocketry/topside/blob/a7c1cda70bfc8ea4d0a2af2e34a7e938741ba68c/topside/plumbing/plumbing_engine.py#L13).
</blockquote></details>

Done.
___
*[tsai_wu.py, line 25 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd4-MrC3ALZmYG2ZEV:-MM8ypHF5DqIIBn4KrlY:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L25)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Same as above; this would be best as a docstring.
</blockquote></details>

Done.
___
*[tsai_wu.py, line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MM3LN0d-NlfmcDTUHj_:-MM8yq6nCFyl-ZOqeEd-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L35)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

Can you do a find and replace "maxstresses" with "maxstress"?
</blockquote></details>

Done.
___
*[tsai_wu.py, line 47 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MM3NcY5Ch3GBQl5ZZAC:-MM8yxH0A7Sq1KataVeA:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L47)):*
<details><summary><i>Previously, kittykong5124 (Shirley Kong) wrote…</i></summary><blockquote>

I think len(height) should be ply_num
</blockquote></details>

Done.
___
*[Code.py, line 116 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLE86BW3ADcG6Cmt-UU:-MM8zrKvAi4wwSmbR7lF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/b2a9e5346ad9df9d2ba57c9a543abae3eb24c4a0/Code.py#L116)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Will do soon
</blockquote></details>

Done.

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @kittykong5124)

___
*[tsai_wu.py, line 64 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/1#-MLd2toC3Qs7W9HjEiMq:-MMDVl3D9zg1tJHyLHfu:b7fi809) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/2e814ac44b3e85dec702228260524e2c31e183f3/tsai_wu.py#L64)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I'm a CS student, not an english student, ok? (on another note, done)
</blockquote></details>

I'm an engineering student, not an English student, ok? (on another note, thanks)

**Pull request merged**
