### PR TITLE
Modularize Code to make it more readable and easier to work with

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Two general comments:

1. There are a lot of small formatting issues (mixed indentation, inconsistent spacing) that could be fixed using the same `format.sh` tool we have in Topside and other repos. If you want to copy that script over to this repo, it will be much easier than trying to fix all of the formatting manually.

2. You've committed a bunch of compiled Python files (`.pyc`). These typically shouldn't be tracked in version control - can you delete them from the PR and create a `.gitignore` with at least the following?

```
__pycache__/
*.py[cod]
```

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-:-MSKFICj0Fmuc_jmlSRA:b-sjwu46)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @KavinSatheeskumar and @kittykong5124)

___
*[ABD_matricies.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDMQb-LZHQgN7h346:-MSKDMQb-LZHQgN7h347:b-99euoo) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L1)):*
> ```Python
> import numpy as np
> ```

this file should be `ABD_matrices.py`
___
*[ABD_matricies.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKD8te8lrb4ahz1Ivj:-MSKD8te8lrb4ahz1Ivk:bwvspw1) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L2)):*
> ```Python
> import numpy as np
> from math import cos, sin, pi
> ```

We already import numpy, so we have `np.sin`, `np.cos`, `np.pi` - no need to import them from `math`
___
*[ABD_matricies.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDJs07-k8NBgi4_5p:-MSKDJs1-GczBYxBNuOv:b-orr6yl) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L8)):*
> ```
> tripple
> ```
triple
___
*[Code.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDSTH6kSJTEqG29_e:-MSKDSTH6kSJTEqG29_f:b8pd1lz) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L1)):*
> ```Python
> #Only works for symmetric ply thicknesses for now
> ```

If this is the main file, it should conventionally be named `main.py`
___
*[Code.py, line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEDMW96783SWrK0l3:-MSKEDMW96783SWrK0l4:bprecyl) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L5)):*
> ```Python
> #Reference: Example page 19 Chapter 8 Lecture Slides for Primary and Principle stress plots
> import numpy as np
> import matplotlib.pyplot as plt
> ```

import is unused, can be removed
___
*[Code.py, line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKD_7B7jy86dS3dtiy:-MSKD_7B7jy86dS3dtiz:bnj7hl0) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L6)):*
> ```Python
> import numpy as np
> import matplotlib.pyplot as plt
> from math import cos, sin, pi
> ```

same as above
___
*[constants.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDjJkAfnJO93_JpIj:-MSKDjJkAfnJO93_JpIk:bnj7hl0) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/constants.py#L2)):*
> ```Python
> import numpy as np
> from math import cos, sin, pi
> ```

same as above
___
*[constants.py, line 32 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDwez3amDDLhIFjMM:-MSKDwez3amDDLhIFjMN:b-lx6y2q) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/constants.py#L32)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> if (len(thickness)%2==1): #Odd number of plies
>     height=np.zeros(len(thickness)+2)
>     stack.insert(mid+int(1),stack[mid]) #Duplicate the middle ply angle
>     thickness[mid]=thickness[mid]/2 #Halve the thickness of the middle ply
>     thickness.insert(mid+1,thickness[mid]) #Duplicate the middle ply thickness
>     print("Odd \n",height,", ",stack,"\n")
> else: #Even number of plies
>     height=np.zeros(len(thickness)+1)
>     print("Even \n",height,", ",stack,"\n")
> height = [np.sum(thickness[0:i])-midplane for i in range(len(height))]
> print("(midplane, height array) ",midplane,", ",height,'\n')
> ```
</details>

A library file shouldn't have any `print` calls in it 
___
*[Q_and_Qbar.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKE5utBkbewhO-nNSu:-MSKE5utBkbewhO-nNSv:bprecyl) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Q_and_Qbar.py#L2)):*
> ```Python
> import numpy as np
> import matplotlib.pyplot as plt
> ```

import is unused, can be removed
___
*[Q_and_Qbar.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKE4IV6cRl1u4UwQsO:-MSKE4IW5EVrob2tC6Om:bnj7hl0) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Q_and_Qbar.py#L3)):*
> ```Python
> import numpy as np
> import matplotlib.pyplot as plt
> from math import sin, cos, pi
> ```

same as above
___
*[stresses_strains.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEM4EBKv7I5cefazc:-MSKEM4EBKv7I5cefazd:bnj7hl0) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L2)):*
> ```Python
> import numpy as np
> from math import cos, sin, pi, ceil
> ```

same as above
___
*[stresses_strains.py, line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEOea-9sqwAHU01b-:-MSKEOea-9sqwAHU01b0:b-n5mhyb) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L7)):*
> ```
> principalStress
> ```
prefer naming this with `snake_case` for consistency (i.e. `principal_stress`)

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @kittykong5124)

___
*[constants.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDjJkAfnJO93_JpIj:-MSmkSb50dXEqL2rbooG:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/constants.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[constants.py, line 32 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDwez3amDDLhIFjMM:-MSmkTIeB1qUMjMRoAZc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/constants.py#L32)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if (len(thickness)%2==1): #Odd number of plies
>     height=np.zeros(len(thickness)+2)
>     stack.insert(mid+int(1),stack[mid]) #Duplicate the middle ply angle
>     thickness[mid]=thickness[mid]/2 #Halve the thickness of the middle ply
>     thickness.insert(mid+1,thickness[mid]) #Duplicate the middle ply thickness
>     print("Odd \n",height,", ",stack,"\n")
> else: #Even number of plies
>     height=np.zeros(len(thickness)+1)
>     print("Even \n",height,", ",stack,"\n")
> height = [np.sum(thickness[0:i])-midplane for i in range(len(height))]
> print("(midplane, height array) ",midplane,", ",height,'\n')
> ```
A library file shouldn't have any `print` calls in it 
</blockquote></details>

Done.
___
*[Q_and_Qbar.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKE5utBkbewhO-nNSu:-MSmkeZg8vr5L6VO2su-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Q_and_Qbar.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

import is unused, can be removed
</blockquote></details>

Done.
___
*[Q_and_Qbar.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKE4IV6cRl1u4UwQsO:-MSmke991-lUHydF5nB3:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Q_and_Qbar.py#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[stresses_strains.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEM4EBKv7I5cefazc:-MSmkfMi276Hy26mxboH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[stresses_strains.py, line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEOea-9sqwAHU01b-:-MSmkg6M65UaVnS8pgpn:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L7)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> principalStress
> ```
prefer naming this with `snake_case` for consistency (i.e. `principal_stress`)
</blockquote></details>

Done.
___
*[ABD_matricies.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDMQb-LZHQgN7h346:-MSmkQny23L9NzUxpRrn:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L1)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

this file should be `ABD_matrices.py`
</blockquote></details>

Done.
___
*[ABD_matricies.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKD8te8lrb4ahz1Ivj:-MSmkQOO16uTa8xv7Mws:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

We already import numpy, so we have `np.sin`, `np.cos`, `np.pi` - no need to import them from `math`
</blockquote></details>

Done.
___
*[ABD_matricies.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDJs07-k8NBgi4_5p:-MSmkROE-ar7oIXe8VbH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/ABD_matricies.py#L8)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> tripple
> ```
triple
</blockquote></details>

Done.
___
*[Code.py, line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEDMW96783SWrK0l3:-MSmkV1PDQv1jaW8pre_:b-iveqgp) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L5)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

import is unused, can be removed
</blockquote></details>

Shirley wanted to use matplotlib later, so I left it in for now

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @jacobdeery and @kittykong5124)

___
*[Code.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKDSTH6kSJTEqG29_e:-MSmkjY176qKCy7-MUc-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L1)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

If this is the main file, it should conventionally be named `main.py`
</blockquote></details>

Done.
___
*[Code.py, line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKD_7B7jy86dS3dtiy:-MSmkkghAe3l69fhzMRE:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/Code.py#L6)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
My comments are mostly addressed. I'll let Shirley review this

> Reviewed 1 of 12 files at r2, 1 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-:-MSo4L4t2VjDxDRJn9sD:bqbxk8v)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @KavinSatheeskumar and @kittykong5124)

___
*[stresses_strains.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEM4EBKv7I5cefazc:-MSo3WDr02utKkxkf0Se:b-1qudz0) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L2)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Numpy also has `ceil`
___
*[stresses_strains.py, line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEOea-9sqwAHU01b-:-MSo3ZCXEgvKDXqg3-a7:bfhqmln) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L7)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[ABD_matrices.py, line 2 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSo3nIW8k5HuH-8MW1c:-MSo3nIW8k5HuH-8MW1d:bg7x8u5) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/6dd3472bfd08f6d0912c3d779b795f861a6909ee/ABD_matrices.py#L2)):*
> ```Python
> import numpy as np
> from Q_and_Qbar import transform_Q
> ```

By convention, these imports should be separated by a single newline

**Comment by jacobdeery** [comment]
I just noticed there are merge conflicts on this PR as well - @KavinSatheeskumar are you able to address these?

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)* status: 2 of 16 files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @kittykong5124)

___
*[stresses_strains.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEM4EBKv7I5cefazc:-MakMm155VbyLSRURUsF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Numpy also has `ceil`
</blockquote></details>

Done.
___
*[stresses_strains.py, line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSKEOea-9sqwAHU01b-:-MakMnlO-Renepns1Bmh:b-7rl0iw) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/875f1e73abd2d96a07578713550155cab16637c3/stresses_strains.py#L7)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

done?
___
*[ABD_matrices.py, line 2 at r3](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-MSo3nIW8k5HuH-8MW1c:-MakMjqwBFiiAtjPV2KF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/composites-calculator/blob/6dd3472bfd08f6d0912c3d779b795f861a6909ee/ABD_matrices.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

By convention, these imports should be separated by a single newline
</blockquote></details>

Done.

**Review by kittykong5124 — APPROVED** [review]
> Reviewed 1 of 13 files at r2, 10 of 14 files at r3, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery)

**Review by kittykong5124 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2#-:-Maq-71-A4ZXJWYNVqTR:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery)

**Review by kittykong5124 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/composites-calculator/2)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery)

**Pull request merged**
